version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '2020:2020'
      - '3030:3030'
    volumes: 
      - './site:/usr/share/nginx/html/site:ro'
      - './dist:/usr/share/nginx/html/dist:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'